In [33]:
import numpy as np
import pandas as pd

In [34]:
np.random.seed(23)

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1

mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0

df = pd.concat([df,df1] , ignore_index = True)
df = df.sample(40)
df.shape

(40, 4)

In [35]:
df

feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
34  0.177061 -0.598109  1.226512       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1
29  1.425140  1.441152  0.182561       0
31  2.224431  0.230401  1.192120       0
4   0.322272  0.060343 -1.043450       1
32 -0.723253  1.461259 -0.085367       0
33  2.823378 -0.332863  2.637391       0
36 -1.389866  0.666726  1.343517       0
18 -0.331617 -1.632386  0.619114       1
0   0.666988  0.025813 -0.777619       1
5  -1.009942  0.441736  1.128877       1
39  0.384865  1.323546 -0.103193       0
22  1.676860  4.187503 -0.080565       0
8   0.241106 -0.952510 -0.136267       1
15 -0.045438  1.040886 -0.094035       1
19 -0.992574 -0.161346  1.192404       1
30  1.437892  1.099723  1.065406       0
25  0.290746  0.866975  0.982643       0
21  0.731858  0.517441  2.244610       0
37 -1.027861  1.131416  2.603234       0
16 -0.420844 -0.551989 -0.121098       1
38 -0.764314  1.566504  1.548788       0
27  2.011059  1.920996  2.933090       0
26  0.898907  0.435960  0.820964       0
23  1.010229  1.437830  2.327788       0
1   0.948634  0.701672 -1.051082       1
10  1.415320  0.457711  0.728876       1
20  1.250737  0.186384  1.703624       0
28  0.204637 -0.011535  3.150780       0
24  0.748855  2.593111  1.170818       0
7   1.045371  0.538162  0.812119       1
6  -1.838068 -0.938769 -0.201841       1
17  0.190141  0.512137  0.131538       1
13 -0.022539  0.013422  0.935945       1
9   1.267248  0.173634 -1.223255       1
35  1.233898  0.052778 -0.261576       0
3   1.772258 -0.347459  0.670140       1

In [36]:
import plotly.express as px
#y_train_trf = y_train.astype(str)
fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
              color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

fig.show()

In [37]:
# Step 1 - Apply standard scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [38]:
df.iloc[:,:3]

feature1  feature2  feature3
2  -0.700809 -1.525586 -1.749156
34 -0.224481 -1.010757  0.491251
14 -0.011456 -0.046935 -0.649616
11  1.342296 -0.962723 -1.184163
12 -2.571350 -0.299561 -0.054040
29  0.867118  0.935791 -0.426437
31  1.566196 -0.219914  0.461019
4  -0.097477 -0.382241 -1.504166
32 -1.011917  0.954984 -0.661960
33  2.090049 -0.757570  1.731490
36 -1.594952  0.196574  0.594105
18 -0.669383 -1.998011 -0.042684
0   0.204020 -0.415201 -1.270487
5  -1.262661 -0.018187  0.405425
39 -0.042731  0.823531 -0.677631
22  1.087278  3.557281 -0.657739
8  -0.168466 -1.349045 -0.706704
15 -0.419084  0.553723 -0.669580
19 -1.247471 -0.593851  0.461269
30  0.878271  0.609885  0.349631
25 -0.125050  0.387719  0.276878
21  0.260757  0.054075  1.386215
37 -1.278334  0.640137  1.701464
16 -0.747423 -0.966733 -0.693369
38 -1.047829  1.055444  0.774549
27  1.379576  1.393819  1.991425
26  0.406862 -0.023700  0.134754
23  0.504227  0.932620  1.459332
1   0.450354  0.229931 -1.510875
10  0.858529 -0.002939  0.053803
20  0.714580 -0.261930  0.910658
28 -0.200363 -0.450851  2.182786
24  0.275623  2.035377  0.442293
7   0.534963  0.073855  0.126978
6  -1.986959 -1.335928 -0.764347
17 -0.213041  0.049013 -0.471289
13 -0.399056 -0.427028  0.235828
9   0.729022 -0.274101 -1.662224
35  0.699853 -0.389462 -0.816857
3   1.170715 -0.771502  0.002171

In [39]:
# Step 2 - Find Covariance Matrix
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]


In [40]:
# Step 3 - Finding Eigen values and eigen vectors
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [41]:
eigen_values

array([1.3536065 , 0.94557084, 0.77774573])

In [42]:
eigen_vectors

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

In [49]:
# for 3D to 2D
pc = eigen_vectors[:2]
pc

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442]])

In [50]:
df.iloc[:,0:3].shape

(40, 3)

In [51]:
pc.T.shape

(3, 2)

So output will be in 40 X 2 means 2 column

In [52]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)
# 40,3 - 3,2
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df.shape

(40, 3)

In [53]:
new_df

PC1       PC2  target
0   0.599433  1.795862       1
1   1.056919 -0.212737       0
2  -0.271876  0.498222       1
3  -0.621586  0.023110       1
4   1.567286  1.730967       1
5  -1.320157 -0.257002       0
6  -0.470834 -1.373121       0
7  -0.401542  1.203061       1
8  -0.433734  1.153326       0
9   0.227326 -2.669841       0
10  1.007007  0.596022       0
11  1.726114  0.492511       1
12 -0.429384  0.829265       1
13  0.886733  0.522664       1
14 -0.872205  0.530675       0
15 -3.367715 -0.254627       0
16  0.688605  0.658084       1
17 -0.478444  0.774372       1
18  1.304549  0.476645       1
19 -0.729043 -0.846506       0
20 -0.069178 -0.130994       0
21  0.484802 -1.217708       0
22  1.058221 -0.452026       0
23  0.741715  1.023822       1
24  0.202775  0.091815       0
25 -0.757890 -2.422615       0
26 -0.138331 -0.368372       0
27 -0.220797 -1.441911       0
28 -1.124520  0.842226       1
29 -0.434777 -0.603836       1
30  0.232113 -1.153250       0
31  1.464336 -1.510939       0
32 -1.348823 -0.536119       0
33 -0.278732 -0.447581       1
34  1.631677  1.894527       1
35 -0.144559  0.494895       1
36  0.623953  0.088371       1
37 -0.997408  0.778938       1
38 -0.497476  0.161370       0
39 -0.094556 -0.761566       1

In [54]:
new_df['target'] = new_df['target'].astype('str')
fig = px.scatter(x=new_df['PC1'],
                 y=new_df['PC2'],
                 color=new_df['target'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()

In [55]:
# for 3D to 1D
pc = eigen_vectors[0]
print('pc : ' , pc)
print('pc shape after transpose : ' ,pc.T.shape )

transformed_df = np.dot(df.iloc[:,0:3],pc.T)
# 40,3 - 3,1
new_df = pd.DataFrame(transformed_df,columns=['PC1'])
new_df['target'] = df['target'].values
new_df.head()

pc :  [-0.53875915 -0.69363291  0.47813384]
pc shape after transpose :  (3,)


PC1  target
0  0.599433       1
1  1.056919       0
2 -0.271876       1
3 -0.621586       1
4  1.567286       1

In [58]:
new_df['target'] = new_df['target'].astype('str')
fig = px.scatter(x=new_df['PC1'],
                 color=new_df['target'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()