In [101]:
import numpy as np
import pandas as pd
from collections import Counter
import operator

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [102]:
df = pd.read_csv('/content/Social_Network_Ads.csv')
df.shape

(400, 5)

In [103]:
df.head(2)

User ID Gender  Age  EstimatedSalary  Purchased
0  15624510   Male   19            19000          0
1  15810944   Male   35            20000          0

In [104]:
x = df.iloc[:,2:4].values
y = df.iloc[:,-1].values

print(x.shape)
print(y.shape)

(400, 2)
(400,)


In [105]:
# train test split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2)

In [106]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(320, 2)
(80, 2)
(320,)
(80,)


In [107]:
x_train[0]

array([   33, 31000])

In [108]:
# scaling values
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [109]:
x_train[0]

array([-0.45531123, -1.14941415])

In [122]:
# class for K Nearest Neighbor

class KNeighborsClassifier:

  def __init__(self , k):
    self.k = k

  def fit(self , x_train , y_train):
    self.x_train = x_train
    self.y_train = y_train
    print('Training Done')

  def predict(self , text_input):
    # print(x_test.shape, x_test.ndim ,sep = '\n')
    # print(x_test[0][0])

    distance = {}
    count = 1

    for row in self.x_train:
      distance [count] = np.sqrt ( (text_input[0][0] - row[0]) ** 2 + (text_input[0][0] - row[1] ) ** 2 )
      count = count + 1

    # kv = key value items ka 1st index ka value de rahe h
    distance = sorted(distance.items() , key = lambda kv : kv[1])

    # now triming first k points
    return self.find_keys(distance [:self.k])



  def find_keys(self , distance):
    indexes = []

    # max = distance[0][0]

    for i in distance:
      indexes.append( i[0] )

    # print(indexes)
    labels = y_train[indexes]
    # print(labels)

    # print(Counter(labels).most_common()[0][0])

    # return the most frequetly used class from y_train
    return Counter(labels).most_common()[0][0]

In [123]:
knn = KNeighborsClassifier(5)
knn.fit(x_train ,y_train)
knn.predict(x_test)

Training Done


1

In [126]:
# making a function to use this model by user

def predict_for_user():
  age = int(input("Enter Age : "))
  sal = int(input('Enter Salary : '))

  input_array = np.array([[age],[sal]]).reshape(1,2)

  input_array = scaler.transform(input_array)

  pred_value = knn.predict(input_array)
  # print( pred_value )

  if pred_value == 0 :
    print('Will Purchased')
  else :
    print("Will not puchased")

In [127]:
predict_for_user()

Enter Age : 53
Enter Salary : 56000
Will not puchased


In [128]:
predict_for_user()

Enter Age : 41
Enter Salary : 47000
Will Purchased


In [121]:
# this is made for testing purpose

# lst = [
#     [52	, 138000	],
#     [20,	82000	],
#     [25	, 22000 ],
#     [31	, 58000	] ,
#     [47	, 105000	],
#     [53	, 82000],
#     [46	, 22000	],
#     [47	,34000	],
#     [42	,70000	],
#     [41	,87000	]
# ]

# for i in lst :
#   predict_for_user(i[0] ,i[1])

[275, 282, 226, 292, 164]
[1 0 1 0 0]
0
None
[55, 88, 297, 42, 117]
[0 0 1 0 1]
0
None
[255, 62, 219, 231, 22]
[1 0 0 0 0]
0
None
[195, 211, 155, 250, 279]
[1 1 1 0 0]
1
None
[121, 152, 285, 145, 194]
[0 0 1 0 0]
0
None
[275, 214, 282, 5, 179]
[1 1 0 0 1]
1
None
[152, 121, 171, 194, 285]
[0 0 1 0 1]
0
None
[121, 152, 285, 145, 194]
[0 0 1 0 0]
0
None
[147, 208, 241, 51, 207]
[0 1 1 0 1]
1
None
[51, 147, 208, 241, 274]
[0 0 1 1 0]
0
None


In [116]:
df.sample(5)

User ID  Gender  Age  EstimatedSalary  Purchased
321  15611191  Female   53            82000          1
209  15697424  Female   46            22000          0
388  15672330    Male   47            34000          1
310  15717893  Female   42            70000          0
378  15577806    Male   41            87000          1