In [24]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.metrics import recall_score,precision_score,f1_score

In [2]:
heart = pd.read_csv('heart.csv')
heart.shape

(303, 14)

In [3]:
heart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [7]:
x = heart.iloc[:,:-1]
y = heart.iloc[:,-1]

x.shape , y.shape

((303, 13), (303,))

In [8]:
x

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [9]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [10]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state = 2)

In [11]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(242, 13)
(61, 13)
(242,)
(61,)


In [12]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [13]:
clf1.fit(x_train,y_train)
clf2.fit(x_train ,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [14]:
y_pred1 = clf1.predict(x_test)
y_pred2 = clf2.predict(x_test)

# Accuracy Score

In [16]:
print('accuracy score for LOGISTIC REGRESSION --> ', accuracy_score(y_test , y_pred1))
print('accuracy score for DECISION TREE --> ', accuracy_score(y_test , y_pred2))

accuracy score for LOGISTIC REGRESSION -->  0.9016393442622951
accuracy score for DECISION TREE -->  0.8032786885245902


# Confusion metrix

In [19]:
print('confusion matrix for LOGISTIC REGRESSION ' )
pd.DataFrame(confusion_matrix(y_test , y_pred1) , columns = [0,1])   # columns = list (range(0,2))

confusion matrix for LOGISTIC REGRESSION 


0   1
0  26   6
1   0  29

In [20]:
print('confusion matrix for DECISION TREE' )
pd.DataFrame(confusion_matrix(y_test , y_pred2) ,  columns = list (range(0,2)) )

confusion matrix for DECISION TREE


0   1
0  23   9
1   3  26

In [23]:
# better understanding
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

result.head(10)

Actual Label  Logistic Regression Prediction  Decision Tree Prediction
99              1                               1                         1
296             0                               1                         0
89              1                               1                         1
30              1                               1                         1
234             0                               0                         1
292             0                               0                         0
35              1                               1                         1
7               1                               1                         1
178             0                               0                         0
13              1                               1                         1

# precision , recall , f1_score

In [25]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  26   6
1   0  29
--------------------------------------------------
Precision -  0.8285714285714286
Recall -  1.0
F1 score -  0.90625


In [29]:
# precision , recall is calculated for all the classes but we get class 1 result in binary classification
precision_score(y_test,y_pred1,average=None)

array([1.        , 0.82857143])

In [32]:
recall_score(y_test,y_pred1,average=None)

array([0.8125, 1.    ])

In [27]:
print("For Decision Tree Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For Decision Tree Model
--------------------------------------------------
    0   1
0  23   9
1   3  26
--------------------------------------------------
Precision -  0.7428571428571429
Recall -  0.896551724137931
F1 score -  0.8125


In [33]:
precision_score(y_test,y_pred2,average=None)

array([0.88461538, 0.74285714])

In [34]:
recall_score(y_test,y_pred2,average=None)

array([0.71875   , 0.89655172])